import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/Card/Card";
import PageTitle from "@/components/PageTitle/PageTitle";
import Toggle from "@/components/Toggle/Toggle";
import MiddleTile from "@/components/MiIddleTile/MiddleTile";
import Card2 from "@/components/Card2/Card2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const cards = 
  [{
    id:"facebook",
    icon:'./images/icon-facebook.svg',
    username:"@nathanf",
    followers:"1987",
    deltafollowers:"12",
    countcolour:"hsl(163, 72%, 41%)",
    arrow:'./images/icon-up.svg',
    bordercolour:"hsl(208, 92%, 53%)",
    label: "FOLLOWERS"
  },
{
    id:"twitter",
    icon:'./images/icon-twitter.svg',
    username:"@nathanf",
    followers:"1044",
    deltafollowers:"99",
    countcolour:"hsl(163, 72%, 41%)",
    arrow:'./images/icon-up.svg',
    bordercolour:"hsl(203, 89%, 53%)",
    label: "FOLLOWERS"
},
{
    id:"instagram",
    icon:'./images/icon-instagram.svg',
    username:"@nathanf",
    followers:"11k",
    deltafollowers:"1099",
    countcolour:"hsl(163, 72%, 41%)",
    arrow:'./images/icon-up.svg',
    bordercolour: '#8A2BE2',
    label: "FOLLOWERS"
},
{
  id:"youtube",
  icon:'./images/icon-youtube.svg',
  username:"@nathanf",
  followers:"8239",
  deltafollowers:"144",
  countcolour:"hsl(356, 69%, 56%)",
  arrow:'./images/icon-down.svg',
  bordercolour:"hsl(348, 97%, 39%)",
  label: "SUBSCRIBERS"
}
]
const display = cards.map((item)=>{
  return <Card key={item.id} icon={item.icon} username= {item.username} followers={item.followers} deltafollowers={item.deltafollowers} countcolour={item.countcolour} arrow={item.arrow} bordercolour={item.bordercolour} label={item.label}/>
})

// const cards2 = [
//   {
//     id:1,

//   }
// ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header>
          <PageTitle/>
          <Toggle/>
        </header>
        <section className={styles.cardsWrapper}>{display}</section>
        <header>
          <MiddleTile/>
        </header>
        <Card2></Card2>
      </main>
    </>
  );
}
